[global]
   workgroup = WORKGROUP
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d
   server role = standalone server
   obey pam restrictions = yes
   unix password sync = yes
   passwd program = /usr/bin/passwd %u
   passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
   pam password change = yes
   map to guest = never
   usershare allow guests = yes
   netbios name = PROJECT-CBM
   disable netbios = yes
   smb ports = 445
   server string = Project CBM

[Project CBM]
   comment = Project CBM Folders
   path = /home/pi/pcbm
   browseable = yes
   read only = no
   guest ok = no
   valid users = pi
   force user = pi
   create mask = 0664
   directory mask = 0775
