#!/bin/bash
#
# ================================================================
#  Project CBM (pcbm)
#  Raspberry Pi Commodore System
#
#  Script: pcbm-release-prep
#  Version: Loaded from /etc/pcbm/version.conf
#
#  Author: Craig Daters
#  Repository: https://github.com/cdaters/project-cbm
#
# ---------------------------------------------------------------
#  Description:
#  This script is part of Project CBM, a lightweight, appliance-
#  style Commodore environment for Raspberry Pi OS using the
#  VICE emulator suite.
#
# ---------------------------------------------------------------
#  License:
#  MIT License. See LICENSE in the project repository.
#
# ---------------------------------------------------------------
#  Credits & Acknowledgements:
#  - Combian64 by Carmelo Maiolino from which this build was inspired
#  - VICE Team, for the Versatile Commodore Emulator
#  - Raspberry Pi Foundation and Raspberry Pi OS developers
#  - Original Commodore engineers and developers
#  - The wider retro-computing and open source communities
#
#  Project CBM does not include or distribute copyrighted ROMs,
#  commercial software, disk images, or game collections.
#
# ---------------------------------------------------------------
#  Notice:
#  You may use, modify, and share this script under the project
#  license, but please preserve attribution where practical.
#
#  No warranty is provided. Use at your own risk.
# ================================================================
#
set -e
echo "Project CBM release prep"
journalctl --rotate
journalctl --vacuum-time=1s
rm -rf ~/.cache/* ~/.thumbnails/* 2>/dev/null || true
rm -f ~/.bash_history
dd if=/dev/zero of=/ZERO.fill bs=16M status=progress || true
rm -f /ZERO.fill
sync
echo "Done. Safe to image + PiShrink."
