#!/bin/bash
#
# ================================================================
#  Project CBM (pcbm)
#  Raspberry Pi Commodore System
#
#  Script: pcbm-firstboot-check
#  Version: Loaded from /etc/pcbm/version.conf
#
#  Author: Craig Daters
#  Repository: https://github.com/cdaters/project-cbm
#
# ---------------------------------------------------------------
#  Description:
#  This script is part of Project CBM, a lightweight, appliance-
#  style Commodore environment for Raspberry Pi OS using the
#  VICE emulator suite.
#
# ---------------------------------------------------------------
#  License:
#  MIT License. See LICENSE in the project repository.
#
# ---------------------------------------------------------------
#  Credits & Acknowledgements:
#  - Combian64 by Carmelo Maiolino from which this build was inspired
#  - VICE Team, for the Versatile Commodore Emulator
#  - Raspberry Pi Foundation and Raspberry Pi OS developers
#  - Original Commodore engineers and developers
#  - The wider retro-computing and open source communities
#
#  Project CBM does not include or distribute copyrighted ROMs,
#  commercial software, disk images, or game collections.
#
# ---------------------------------------------------------------
#  Notice:
#  You may use, modify, and share this script under the project
#  license, but please preserve attribution where practical.
#
#  No warranty is provided. Use at your own risk.
# ================================================================
#

echo "Project CBM first boot validation"
df -h /
systemctl is-active smbd || true
systemctl is-active avahi-daemon || true
command -v x64sc >/dev/null && echo "VICE present"
